### ISSUE TITLE
Delicious Issues

### ISSUE THREAD

**Issue by nujaidyy** [drichardson/DeliciousSafari#10]
1) Error on saving bookmark, and the error states something about Error on Deleting !
2) Could not delete TAG's from existing Bookmark

I am using:
Safari 8.0.5  on OS X Yosemite

**Comment by meetconverge** [comment]
I have the exact same issues.. Safari 8.0.5 on OS X Yosemite as well..

I only saw an error once, now it doesn't even show the error, but doesn't save either.

**Comment by nujaidyy** [comment]
The tool is excellent, and wish it gets fixed quickly. I have been searching for Delicious tool, and even the Delicious own tool does not match this component.

**Comment by nujaidyy** [comment]
Is this project still alive and being updated? The tool is too good to be ignored.

**Comment by drichardson** [comment]
@nujaidyy, no, I haven't made any changes in quite a while.

**Comment by nujaidyy** [comment]
It is excellent component and regrettably needs fixing SAVE BOOKMARK button
as it does not work.

I hope you do not get offended by me asking if you are willing to white
labrl it and continue supporting and enhance it for a fee? In other words,
do you render your services as freelancer?

**Comment by drichardson** [comment]
@nujaidyy, no, I'm not doing freelance work at the moment and I am working on another project that's taking all my time right now.

Originally, this was a shareware application, but then a few years ago decided to start winding it down due to 1) low demand and 2) the introduction of officially supported Safari extensions. When I ended the shareware aspect of the plugin I opened sourced it so it could (hopefully) live a longer life. Unfortunately, besides Ivan who removed the shareware license checks, no one else has contributed.

**Comment by drichardson** [comment]
And for the record, I'd be more than happy for Delicious itself to take over this project.

**Comment by nujaidyy** [comment]
Thanks for your work and wish you best of luck in whatever you do.

Whenever you are willing to do freelance work, please do let me know.

Thank

Yaagoub

**Comment by drichardson** [comment]
I'm officially closing down this project, so this issue won't be fixed. [See  here](http://delicioussafari.com/) for more details.
